# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beb3e4105880fd87a0b4b331def34afd3b61abe5aed8346a013f8bcac17a72232a501c182e973300cbfd1be207caf47ebc0dc1bc8c8203187c0c134cb4d7c0ef

test:
  secret_key_base: 38cc87b0a14bca3dba6e4e377d4c4ad1ff074490fc7f28f40a1403fec529d461cf4c5840e84a6b2d44b889bcee350e25be60c6472dc5ed96299fe61e7049b81a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
